image: node:14.17.6

pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
    - npm i -g @angular/cli@14.1.3
    - npm i
    - npm run buildProd
    - mkdir -p public
    - mv dist/aprosaigneur/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - main
